config/routes.rb
Rails.application.routes.draw do

  root 'follows#index'

  resources :users, :posts, :follows, :sessions

end

app/models/favorite_post.rb
class FavoritePost < ActiveRecord::Base
  belongs_to :feed
  has_one :user, through: :feed
  has_many :posts
end

app/models/favorite_posts.rb
class FavoritePost < ActiveRecord::Base
  belongs_to :feed
  belongs_to :user, through: :feed
  has_many :posts
end

app/models/follow.rb
class Follow < ActiveRecord::Base
  belongs_to :subscriber, class_name: 'User', foreign_key: "subscriber_id"
  belongs_to :subscribee, class_name: 'User', foreign_key: "followed_user_id"
  # has_many :favorite_posters, source: :user
  # has_many :feed_posts, through: :favorite_posters, source: :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :follows, through: :user, foreign_key: 'followed_user_id'
  has_many :subscribers, through: :follows, class_name: 'User'
  has_many :favorite_posts
  has_many :followers, through: :follows, source: :user
end

app/models/posts.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :feeds, :favorite_posts
  has_many :followers, through: :feeds, source: :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :subscriptions, class_name: "Follow", foreign_key: 'subscriber_id'
  has_many :follows, class_name: "Follow", foreign_key: 'followed_user_id'
  has_many :favorite_posters, through: :subscriptions, source: :subscribee#class_name: 'User', foreign_key: 'subscriber_id'
  has_many :subscribers, through: :follows, source: :subscriber

  has_secure_password

  def favorite_posts
    ids = self.favorite_posters.pluck(:id)
    Post.joins(:follows).where(follows: {subscriber_id: self.id}).where(follows: {followed_user_id: ids})
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController

  def index
    @posts = Post.all
  end

  def show
    @feed = Feed.find(params[:id])
  end

end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController

  def index
    @posts = Post.all
  end

  def show
    owner = User.find(params[:id])
    @posts = owner.favorite_posts
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
  end

  def show
    @owner = User.find(params[:id])
    @posts = @owner.favorite_posts.order(created_at: :desc)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/follows/_post.html.erb
<div class="post">
  <p><%= post.text %></p>
  <p class = "sig"><%= link_to post.user.username, post.user %></p>
</div>

app/views/follows/index.html.erb
<%= render @posts %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Critter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <h1><%= link_to 'critter', root_path %></h1>
  <h2>Find a community of Latin-speaking animals.</h2>
  <a href="/"><img src="/assets/github-01.svg"></a>
</header>
<nav>
  <%= link_to 'Users', users_path %>
</nav>
<%= yield %>

</body>
</html>

app/views/posts/_post.html.erb
<div class="post">
  <p><span class = "name"><%= link_to post.user.username, post.user %></span> <span class="date"><%= post.created_at %></span></p>
  <p><%= post.text %></p>
</div>

app/views/posts/index.html.erb
<h1>Post feed</h1>

<%= render @posts %>

app/views/posts/show.html.erb
<h2><%= link_to @owner.username, user_path(@owner) %>'s feed</h2>

<%= render @posts %>

app/views/users/_avatar_script.html.erb
<script>

$(document).ready(function() {
  var species = $("#species").text();
  var search_url = "http://api.pixplorer.co.uk/image?word=animal+" + species;
  var request = $.ajax({
    type: "GET",
    url: search_url,
    dataType: 'json'
  });
  request.done(function(response){
    var img_url = response.images[0].imageurl;
    var img_html = "<img src='" + img_url + "'>";
    $("#avatar").append(img_html);
  });
})

</script>

app/views/users/_user.html.erb
<div class="user">
<h1><%= link_to user.username, user_path(user.id) %></h1>

<div id="avatar"></div>

<h2 id="species"><%= user.species %></h2>
<p>registered on <%= user.created_at %></p>
<p><%= user.subscribers.count %> followers | <%= link_to 'following', post_path(user.id)%> <%= user.favorite_posters.count %> users</p>
</div>

app/views/users/index.html.erb
<%= render @users %>

app/views/users/show.html.erb
<script>

$(document).ready(function() {
  var species = $("#species").text();
  var search_url = "http://api.pixplorer.co.uk/image?word=animal+" + species;
  var request = $.ajax({
    type: "GET",
    url: search_url,
    dataType: 'json'
  });
  request.done(function(response){
    var img_url = response.images[0].imageurl;
    var img_html = "<img src='" + img_url + "'>";
    $("#avatar").append(img_html);
  });
})

</script>

<h1><%= @user.username %></h1>

<div id="avatar"></div>

<h2 id="species"><%= @user.species %></h2>
<p>registered on <%= @user.created_at %></p>
<p><%= @user.subscribers.count %> followers | <%= link_to 'following', post_path(@user.id)%> <%= @user.favorite_posters.count %> users</p>
<h3><%= @user.username %>'s posts:</h3>
<%= render @user.posts %>